### ISSUE TITLE
Implementation difference between CoDATS and DANN

### ISSUE THREAD

**Issue by jaeho3690** [emadeldeen24/AdaTime#11]
Thank you once again for sharing the code.

I am currently implementing CoDATS and DANN. From the original paper, CoDATS seems to be just DANN applied to time series, and I also see that the implementation of CoDATS and DANN from your work are almost identical, except the classification head where CoDATS has 3, and DANN has a single classifier head. Is this difference simply a design choice? or was there any other references? If so, could you please kindly share one?

Thank you!

**Comment by emadeldeen24** [comment]
DANN is not designed specifically for time series, so we used a single head just like what we did for all other non-time-series works. CoDATS is for TS, and we followed the authors' code.
