### ISSUE TITLE
Number of sweeps provided as argument ignored

### ISSUE THREAD

**Issue by ghost** [emadeldeen24/AdaTime#4]
Hi emadeldeen24,
I'm trying to reproduce the results listed in your paper with the following setup:
`python main.py --experiment_description domain-adapt-test --run_description domain-adapt-run --da_method Deep_Coral --dataset HAR --sweep_project_wandb domain-adapt-sweep --num_runs 1 --device cpu --is_sweep True --num_sweeps 1`
Somehow the parameter is ignored and wandb runs an infinite number of sweeps (stopped run at 50) nevertheless.
Can you help?
Thanks a lot,
Nicole

**Comment by emadeldeen24** [comment]
Hi,
please make sure that the `--hp_search_strategy` is not set to `grid`. Otherwise, try to use the same packages versions described in the ReadMe file.
