### ISSUE TITLE
I found this error about config.py of WISDOM

### ISSUE THREAD

**Issue by Afleve** [emadeldeen24/AdaTime#9]
I can run these dataset(HAR)
But I met this error when I run this on WISDOM  using CoTMix
![1](https://github.com/emadeldeen24/AdaTime/assets/54371604/6e8b45d2-5045-477b-8242-e4c636bf55d5)
cuz the WISDOM class hasn't step_size and lr_decay in the config.py

 one more error:
![2](https://github.com/emadeldeen24/AdaTime/assets/54371604/38f6a064-d8c0-407e-b30a-8b250ef7f8cb)
cuz the size of trg isn't equal to the size of src in the last batch.

**Comment by emadeldeen24** [comment]
you can set `drop_last = True` in the dataloader

**Comment by NicolasKhms** [comment]
@Onenormler Were you able to solve the step_size and lr_decay error?
